name: 02-01-CICD
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # with:
      #   repository: TCS/Nextgen
      #   token: "${ secrets.'nextgen-devops-token'\n }"
      #   ref: DevOps
    - name: Build
      run: | 
        #!/bin/bash
        mvn clean package
        echo maven completed
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
