
name: git-mvn-docker-test
on:
  workflow_dispatch:
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      with:
        repository: DaggupatiPavan/java-web-app-docker
    - name: sh
      shell: bash
      run: mvn clean package
    # - name: sh
    #   shell: bash
    #   run: |
    #     sudo docker build -t pavan176/webapp .
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: pavan176/webapp:v.0.1
