name: Data Collection on Self-Hosted Runner

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  clone:
    name: clone
    runs-on: self-hosted # Use the self-hosted runner
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
        

                
      - name: Use Build Output
        run: |
          echo "Build took ${{ steps.build.outputs.duration }}ms"
          echo "Build status: ${{ steps.build.outputs.status }}"
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          repository: DaggupatiPavan/java-web-app-docker
  
      - name: Upload workspace to artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: . 
  Build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Download workspace from artifact
      uses: actions/download-artifact@v3
      with:
        name: workspace  # Matches the artifact name from the 'setup' job
        path: .
    - name: sh
      shell: bash
      run: mvn clean package

    - name: Upload workspace to artifact
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: . 

  Build2:
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Download workspace from artifact
      uses: actions/download-artifact@v3
      with:
        name: workspace  # Matches the artifact name from the 'setup' job
        path: .
    - name: sh
      shell: bash
      run: echo "done"

    - name: Upload workspace to artifact
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: .      

  ImageBuild:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Download workspace from artifact
      uses: actions/download-artifact@v3
      with:
        name: workspace  # Matches the artifact name from the 'setup' job
        path: .
    - name: install ncc
      run: |
        npm install ncc
        
    - name: Run tests with metrics
      uses: DaggupatiPavan/test-action2@v1
      id: test-metrics
      with:
        command: 'npm test'
    
    - name: Log test metrics
      run: |
        echo "Test execution time: ${{ steps.test-metrics.outputs.duration }}ms"
        echo "Test output: ${{ steps.test-metrics.outputs.stdout }}"
    
